# Generated by Django 3.2.5 on 2021-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('fat_btn', models.IntegerField(default=0)),
                ('dumb_btn', models.IntegerField(default=0)),
                ('stupid_btn', models.IntegerField(default=0)),
            ],
        ),
    ]
