# Generated by Django 3.2.5 on 2021-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telebot',
            name='user',
        ),
        migrations.AddField(
            model_name='telebot',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telebot',
            name='userid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telebot',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
