# Generated by Django 3.2.5 on 2021-07-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210726_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telebot',
            name='dumb_btn',
        ),
        migrations.RemoveField(
            model_name='telebot',
            name='fat_btn',
        ),
        migrations.RemoveField(
            model_name='telebot',
            name='stupid_btn',
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.telebot')),
            ],
        ),
    ]
